
version: 2

models:
  - name: users
    description: "A user dbt model"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        description: "The primary key for this table"
        data_type: int
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: first_name
        description: "The user's first name"
        data_type: varchar(50)
        tests:
          - not_null
      - name: last_name
        description: "The user's last name"
        data_type: varchar(50)
        tests:
          - not_null
      - name: age
        description: "The user's age"
        data_type: int
        tests:
          - not_null