apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: karapace-rest
  name: karapace-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: karapace-rest
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: karapace-rest
    spec:
      containers:
        - command:
            - /bin/bash
            - /opt/karapace/start.sh
            - rest
          env:
            - name: KARAPACE_ADMIN_METADATA_MAX_AGE
              value: "0"
            - name: KARAPACE_ADVERTISED_HOSTNAME
              value: karapace-rest
            - name: KARAPACE_BOOTSTRAP_URI
              value: redpanda-0:19092
            - name: KARAPACE_HOST
              value: 0.0.0.0
            - name: KARAPACE_LOG_LEVEL
              value: WARNING
            - name: KARAPACE_PORT
              value: "8084"
            - name: KARAPACE_REGISTRY_HOST
              value: karapace-registry
            - name: KARAPACE_REGISTRY_PORT
              value: "8085"
          image: ghcr.io/aiven-open/karapace:develop
          name: karapace-rest
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
