apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mc
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mc
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - " /usr/bin/mc config; until (/usr/bin/mc config host add minio http://minio-0:9301  ) do echo '...waiting...' && sleep 1;  done;  /usr/bin/mc mb minio/; /usr/bin/mc policy set public minio/;  /usr/bin/mc mb minio/; /usr/bin/mc policy set public minio/; \nexit 0;  "
          image: minio/mc
          name: mc
      hostname: mc
      restartPolicy: Always
