apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: minio-0
  name: minio-0
spec:
  ports:
    - name: "9301"
      port: 9301
      targetPort: 9301
    - name: "9400"
      port: 9400
      targetPort: 9400
    - name: 9301-tcp
      port: 9301
      targetPort: 9301
    - name: 9400-tcp
      port: 9400
      targetPort: 9400
  selector:
    io.kompose.service: minio-0
