receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
      - job_name: 'redpanda'
        scrape_interval: 10s
        static_configs:
        - targets: ['redpanda-0:9644']

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]