apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: postgres-0
  name: postgres-0
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres-0
