apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redpanda-console
  name: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redpanda-console
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f json-defaultpartitioned-to-json/docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: redpanda-console
    spec:
      containers:
        - args:
            - -c
            - echo "$(CONSOLE)_CONFIG_FILE" > /tmp/config.yml; /app/console
          command:
            - /bin/sh
          env:
            - name: CONFIG_FILEPATH
              value: /tmp/config.yml
            - name: CONSOLE_CONFIG_FILE
              value: |
                kafka:
                  brokers: ["redpanda-0:19092"]
                  schemaRegistry:
                    enabled: true
                    urls: ["http://karapace-registry:8085"]
                connect:
                  enabled: true
                  clusters:
                    - name: local-connect-cluster
                      url: http://connect:8083
                redpanda:
                  adminApi:
                    enabled: true
                    urls: ["http://redpanda-0:9644"]
          image: docker.redpanda.com/redpandadata/console:v2.6.0
          name: redpanda-console
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
